apiVersion: v1
kind: Service
metadata:
  name: arkpz-api
spec:
  type: NodePort
  selector:
    app: arkpz-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkpz-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkpz-api
  template:
    metadata:
      labels:
        app: arkpz-api
    spec:
      containers:
        - name: arkpz-api
          image: mkolesh/arkpz-api
          ports:
            - containerPort: 5000
          env:
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "12345"
            - name: DB_HOST
              value: "arkpz-postgres"
            - name: DB_PORT
              value: "5432"
