apiVersion: apps/v1
kind: Deployment
metadata:
  name: arkpz-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arkpz-api
  template:
    metadata:
      labels:
        app: arkpz-api
    spec:
      containers:
        - name: arkpz-api
          image: mkolesh/arkpz-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "12345"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
